version: '3'

services:
  application-product:
    build: application-product
    mem_limit: 512m
    ports: 
    - "8096:8096"
    environment:
      DB_URL: jdbc:postgresql://product_db:5432/product
      DB_USER: #user
      DB_PASSWORD: #contraseña
    restart: always
    depends_on:
      product_db:
        condition: service_healthy
  product_db:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: #user
      POSTGRES_PASSWORD: #contraseña
      POSTGRES_DB: product
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Este comando prueba si la base de datos acepta conexiones
      test: ["CMD-SHELL", "pg_isready -U user -d product"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data: